name: Test
on:
  push:
    branches-ignore:
      - magick
      - 'gh-readonly-queue/**'
  pull_request:
  merge_group:
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable
      - run: cargo fmt -- --check
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo test
      - run: cargo doc
